### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by radare** [tapquo/Lungo.js#129]
Current code in git does not compiles. Looks like there are some missing files. Am I doing something wrong?

Also, using echo -e is not portable. You may use printf program to honor escape codes.

git commit: 9e68372abc25ece1c4f752d52820fdbaacf30fc5

output of build.sh:

```
-e ============================ LUNGO COMPILER ============================
-e   [DIR]: ../src/
-e   [DIR]: ../src/router/
-e   [DIR]: ../src/view/
-e   [DIR]: ../src/element/
-e   [DIR]: ../src/data/
-e   [DIR]: ../src/attributes/
-e   [DIR]: ../src/boot/
java.io.FileNotFoundException: ../package/lungo.js (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:84)
    at com.google.javascript.jscomp.AbstractCommandLineRunner.fileNameToOutputWriter(Unknown Source)
    at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(Unknown Source)
    at com.google.javascript.jscomp.AbstractCommandLineRunner.run(Unknown Source)
    at com.google.javascript.jscomp.CommandLineRunner.main(Unknown Source)
-e   [BUILD]: lungo.js
-e   [DIR]: ../src/stylesheets/css/ >> COMPRESSING
java.io.FileNotFoundException: ../src/stylesheets/css/Lungo.widgets.colour.css (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at java.io.FileInputStream.<init>(FileInputStream.java:79)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:20)
build.sh: line 109: ../package//lungo.css: No such file or directory
-e     [BUILD]: lungo.css
rm: ../src/stylesheets/css/Lungo.widgets.colour.min.css: No such file or directory
-e     [BUILD]: lungo.icon.css
cp: ../package/lungo.icon.css: No such file or directory
-e     [BUILD]: lungo.icon.brand.css
cp: ../package/lungo.icon.brand.css: No such file or directory
-e     [BUILD]: lungo.theme.default.css
cp: ../package/lungo.theme.default.css: No such file or directory
-e     [COPY]: lungo.theme.default.less
cp: ../src/stylesheets/lungo.theme.default.less: No such file or directory
-e     [COPY]: mixins.less
cp: ../src/stylesheets/mixins.less: No such file or directory
============================ /LUNGO COMPILER ============================
```

**Comment by radare** [comment]
As discussed in the closed forums (google groups) part of the problem can be fixed by just "mkdir package".

I have created a pullrequest to fix the bashisms from the script and also added the magic 'mkdir' line. but still fails, here's the error after creating the 'package' directory:

```
java.io.FileNotFoundException: ../src/stylesheets/css/Lungo.widgets.colour.css (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:97)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:20)
cat: ../src/stylesheets/css/Lungo.widgets.colour.min.css: No such file or directory
    [BUILD]: lungo.css
rm: cannot remove ‘../src/stylesheets/css/Lungo.widgets.colour.min.css’: No such file or directory
    [BUILD]: lungo.icon.css
    [BUILD]: lungo.icon.brand.css
    [BUILD]: lungo.theme.default.css
    [COPY]: lungo.theme.default.less
cp: cannot stat ‘../src/stylesheets/lungo.theme.default.less’: No such file or directory
    [COPY]: mixins.less
cp: cannot stat ‘../src/stylesheets/mixins.less’: No such file or directory
```

**Comment by soyjavi** [comment]
FIXED :)
